function onCreatePost()
makeLuaSprite('whitebg', '', -1000, -500)
setScrollFactor('whitebg', 0, 0)
makeGraphic('whitebg', 1000, 1000, 'ffffff')
setProperty('whitebg.alpha', 0)
scaleObject('whitebg',4,4)
addLuaSprite('whitebg', false)
end
function onEvent(n, v1, v2)
	if n == 'badapplelol' and string.lower(v1) == 'a' then
		doTweenAlpha('lollal90', 'whitebg', 1, v2, 'linear')
		doTweenColor('lollal', 'boyfriend', '000000', v2, 'linear')
		doTweenColor('lollal1', 'dad', '000000', v2, 'linear')
		doTweenColor('lollal2', 'gf', '000000', v2, 'linear')
		doTweenColor('lollal3', 'pcn_new_pibby', '000000', v2, 'linear')
		doTweenColor('lollal4', 'jake', '000000', v2, 'linear')
		doTweenColor('lollal5', 'perla', '000000', v2, 'linear')
		doTweenAlpha('apple', 'healthBar', 0, v2, 'linear')
		doTweenAlpha('apple1', 'iconbar', 0, v2, 'linear')
		doTweenAlpha('apple2', 'ola', 0, v2, 'linear')
		doTweenAlpha('apple3', 'yo', 0, v2, 'linear')
		doTweenAlpha('apple4', 'healthBarBG', 0, v2, 'linear')
		doTweenAlpha('nath', 'iconP1', 0, v2, 'linear')
		doTweenAlpha('nath2', 'iconP2', 0, v2, 'linear')
		doTweenAlpha('juepucta', 'scoreTxt', 0, v2, 'linear')
		doTweenAlpha('juepucta1', 'pibby', 0, v2, 'linear')
		doTweenAlpha('juepucta2', 'pibbyl', 0, v2, 'linear')
		doTweenAlpha('juepucta3', 'Jake', 0, v2, 'linear')
		doTweenAlpha('juepucta4', 'jakel', 0, v2, 'linear')
		doTweenAlpha('juepucta5', 'cup', 0, v2, 'linear')
		doTweenAlpha('juepucta6', 'cupl', 0, v2, 'linear')
	end
	if n == 'badapplelol' and string.lower(v1) == 'f' then
		doTweenAlpha('lollal90', 'whitebg', 1, v2, 'linear')
		doTweenAlpha('apple', 'healthBar', 0, v2, 'linear')
		doTweenAlpha('apple1', 'iconbar', 0, v2, 'linear')
		doTweenAlpha('apple2', 'ola', 0, v2, 'linear')
		doTweenAlpha('apple3', 'yo', 0, v2, 'linear')
		doTweenAlpha('apple4', 'healthBarBG', 0, v2, 'linear')
		doTweenAlpha('nath', 'iconP1', 0, v2, 'linear')
		doTweenAlpha('nath2', 'iconP2', 0, v2, 'linear')
		doTweenAlpha('juepucta', 'scoreTxt', 0, v2, 'linear')
		doTweenAlpha('juepucta1', 'pibby', 0, v2, 'linear')
		doTweenAlpha('juepucta2', 'pibbyl', 0, v2, 'linear')
		doTweenAlpha('juepucta3', 'Jake', 0, v2, 'linear')
		doTweenAlpha('juepucta4', 'jakel', 0, v2, 'linear')
		doTweenAlpha('juepucta5', 'cup', 0, v2, 'linear')
		doTweenAlpha('juepucta6', 'cupl', 0, v2, 'linear')
	end
	if n == 'badapplelol' and string.lower(v1) == 'n' then
		doTweenAlpha('lollal90', 'whitebg', 1, v2, 'linear')
		doTweenAlpha('apple', 'healthBar', 0, v2, 'linear')
		doTweenAlpha('apple1', 'iconbar', 0, v2, 'linear')
		doTweenAlpha('apple2', 'ola', 0, v2, 'linear')
		doTweenAlpha('apple3', 'yo', 0, v2, 'linear')
		doTweenAlpha('apple4', 'healthBarBG', 0, v2, 'linear')
		doTweenAlpha('nath', 'iconP1', 0, v2, 'linear')
		doTweenAlpha('nath2', 'iconP2', 0, v2, 'linear')
		doTweenAlpha('juepucta', 'scoreTxt', 0, v2, 'linear')
		doTweenAlpha('juepucta1', 'pibby', 0, v2, 'linear')
		doTweenAlpha('juepucta2', 'pibbyl', 0, v2, 'linear')
		doTweenAlpha('juepucta3', 'Jake', 0, v2, 'linear')
		doTweenAlpha('juepucta4', 'jakel', 0, v2, 'linear')
		doTweenAlpha('juepucta5', 'cup', 0, v2, 'linear')
		doTweenAlpha('juepucta6', 'cupl', 0, v2, 'linear')
	end
	if n == 'badapplelol' and string.lower(v1) == 'col b' then
		setProperty('gf.color', getIconColor('gf'))
		setProperty('dad.color', getIconColor('dad'))
		setProperty('boyfriend.color', getIconColor('boyfriend'))
		doTweenColor('pibyyyyy2', 'pcn_new_pibby', '87cefa', v2, 'linear')
        doTweenColor('jakeeeee2', 'jake', 'FFFF00', v2, 'linear')
		doTweenAlpha('lollal90', 'whitebg', 1, v2, 'linear')
		doTweenAlpha('apple', 'healthBar', 0, v2, 'linear')
		doTweenAlpha('apple1', 'iconbar', 0, v2, 'linear')
		doTweenAlpha('apple2', 'ola', 0, v2, 'linear')
		doTweenAlpha('apple3', 'yo', 0, v2, 'linear')
		doTweenAlpha('apple4', 'healthBarBG', 0, v2, 'linear')
		doTweenAlpha('nath', 'iconP1', 0, v2, 'linear')
		doTweenAlpha('nath2', 'iconP2', 0, v2, 'linear')
		doTweenAlpha('juepucta', 'scoreTxt', 0, v2, 'linear')
		doTweenAlpha('juepucta1', 'pibby', 0, v2, 'linear')
		doTweenAlpha('juepucta2', 'pibbyl', 0, v2, 'linear')
		doTweenAlpha('juepucta3', 'Jake', 0, v2, 'linear')
		doTweenAlpha('juepucta4', 'jakel', 0, v2, 'linear')
		doTweenAlpha('juepucta5', 'cup', 0, v2, 'linear')
		doTweenAlpha('juepucta6', 'cupl', 0, v2, 'linear')
	end
	if n == 'badapplelol' and string.lower(v1) == 'col w' then
		setProperty('gf.color', getIconColor('gf'))
		setProperty('dad.color', getIconColor('dad'))
		setProperty('boyfriend.color', getIconColor('boyfriend'))
		doTweenColor('pibyyyyy2', 'pcn_new_pibby', '87cefa', v2, 'linear')
        doTweenColor('jakeeeee2', 'jake', 'FFFF00', v2, 'linear')
		doTweenAlpha('lollal90', 'whitebg', 1, v2, 'linear')
		doTweenAlpha('apple', 'healthBar', 0, v2, 'linear')
		doTweenAlpha('apple1', 'iconbar', 0, v2, 'linear')
		doTweenAlpha('apple2', 'ola', 0, v2, 'linear')
		doTweenAlpha('apple3', 'yo', 0, v2, 'linear')
		doTweenAlpha('apple4', 'healthBarBG', 0, v2, 'linear')
		doTweenAlpha('nath', 'iconP1', 0, v2, 'linear')
		doTweenAlpha('nath2', 'iconP2', 0, v2, 'linear')
		doTweenAlpha('juepucta', 'scoreTxt', 0, v2, 'linear')
		doTweenAlpha('juepucta1', 'pibby', 0, v2, 'linear')
		doTweenAlpha('juepucta2', 'pibbyl', 0, v2, 'linear')
		doTweenAlpha('juepucta3', 'Jake', 0, v2, 'linear')
		doTweenAlpha('juepucta4', 'jakel', 0, v2, 'linear')
		doTweenAlpha('juepucta5', 'cup', 0, v2, 'linear')
		doTweenAlpha('juepucta6', 'cupl', 0, v2, 'linear')
	end
	if n == 'badapplelol' and string.lower(v1) == 'b' then
		doTweenAlpha('lollal90', 'whitebg', 0, v2, 'linear')
		doTweenColor('lollal', 'boyfriend', 'FFFFFF', v2, 'linear')
		doTweenColor('lollal1', 'dad', 'FFFFFF', v2, 'linear')
		doTweenColor('lollal2', 'gf', 'FFFFFF', v2, 'linear')
		doTweenColor('lollal3', 'pcn_new_pibby', 'FFFFFF', v2, 'linear')
		doTweenColor('lollal4', 'jake', 'FFFFFF', v2, 'linear')
		doTweenColor('lollal5', 'perla', 'FFFFFF', v2, 'linear')
		doTweenAlpha('apple', 'healthBar', 1, v2, 'linear')
		doTweenAlpha('apple1', 'iconbar', 1, v2, 'linear')
		doTweenAlpha('apple2', 'ola', 1, v2, 'linear')
		doTweenAlpha('apple3', 'yo', 1, v2, 'linear')
		doTweenAlpha('apple4', 'healthBarBG', 1, v2, 'linear')
		doTweenAlpha('nath', 'iconP1', 1, v2, 'linear')
		doTweenAlpha('nath2', 'iconP2', 1, v2, 'linear')
		doTweenAlpha('juepucta', 'scoreTxt', 1, v2, 'linear')
		doTweenAlpha('juepucta1', 'pibby', 1, v2, 'linear')
		doTweenAlpha('juepucta2', 'pibbyl', 1, v2, 'linear')
		doTweenAlpha('juepucta3', 'Jake', 1, v2, 'linear')
		doTweenAlpha('juepucta4', 'jakel', 1, v2, 'linear')
		doTweenAlpha('juepucta5', 'cup', 1, v2, 'linear')
		doTweenAlpha('juepucta6', 'cupl', 1, v2, 'linear')
	end
	if n == 'badapplelol' and string.lower(v1) == 'c' then
		doTweenAlpha('lollal90', 'whitebg', 1, v2, 'linear')
		doTweenColor('lollal', 'boyfriend', '000000', v2, 'linear')
		doTweenColor('lollal1', 'dad', '000000', v2, 'linear')
		doTweenColor('lollal2', 'gf', '000000', v2, 'linear')
		doTweenColor('lollal3', 'pcn_new_pibby', '000000', v2, 'linear')
		doTweenColor('lollal4', 'jake', '000000', v2, 'linear')
		doTweenColor('lollal5', 'perla', '000000', v2, 'linear')
		setShaderInt("pcn_new_pibby", "invert", 1)
		setShaderInt("perla", "invert", 1)
		setShaderInt("whitebg", "invert", 1)
		doTweenAlpha('apple', 'healthBar', 0, v2, 'linear')
		doTweenAlpha('apple1', 'iconbar', 0, v2, 'linear')
		doTweenAlpha('apple2', 'ola', 0, v2, 'linear')
		doTweenAlpha('apple3', 'yo', 0, v2, 'linear')
		doTweenAlpha('apple4', 'healthBarBG', 0, v2, 'linear')
		doTweenAlpha('nath', 'iconP1', 0, v2, 'linear')
		doTweenAlpha('nath2', 'iconP2', 0, v2, 'linear')
		doTweenAlpha('juepucta', 'scoreTxt', 0, v2, 'linear')
		doTweenAlpha('juepucta1', 'pibby', 0, v2, 'linear')
		doTweenAlpha('juepucta2', 'pibbyl', 0, v2, 'linear')
		doTweenAlpha('juepucta3', 'Jake', 0, v2, 'linear')
		doTweenAlpha('juepucta4', 'jakel', 0, v2, 'linear')
		doTweenAlpha('juepucta5', 'cup', 0, v2, 'linear')
		doTweenAlpha('juepucta6', 'cupl', 0, v2, 'linear')
	end
end

function getIconColor(chr)
    return getColorFromHex(rgbToHex(getProperty(chr .. ".healthColorArray")))
end
function rgbToHex(array)
    return string.format('%.2x%.2x%.2x', array[1], array[2], array[3])
end